Pipeline for Ammersee (owner Niels Digemmanse)
SPI-Birds/pipelines pull request #111
Opened 2020-06-02 10:27 UTC by LiamDBailey

2020-06-02 10:33 UTC, LiamDBailey commented
@ChloeRN I had to make some changes to other pipelines to avoid errors on windows. You can just focus on the changes to `format_AMM` and `test_AMM_pipeline` because these are the most relevant.

2020-08-13 15:54 UTC, LiamDBailey commented
@StefanVriend added you to review. Maybe give it a try and see if it runs/passes the tests on your system. Feel free to leave other comments/reviews on the code if you feel like it 😄

2020-08-31 13:34 UTC, StefanVriend requested changes
Running `run_pipelines(PopID = "Amm")` resulted in the following error: `Error: Column 'Habitat' not found in '.data'`. See comment on "format_AMM.R".

2020-08-31 13:34 UTC, StefanVriend commented on R/format_AMM.R
> +                  .data$Habitat)
After checking out origin/AMM_pipeline, I ran `run_pipelines(PopID = "AMM", save = FALSE)`, which resulted in an error related to these lines: `Error: Column 'Habitat' not found in '.data'`

2020-09-02 09:53 UTC, LiamDBailey commented
New commits should fix those issues (didn't notice that I changed one of the column names 🤦). @StefanVriend could you try running it again? I think it should be fine now.

2020-09-02 10:01 UTC, StefanVriend commented
Yes! I can confirm that the pipeline and the tests run flawlessly now. 
I cannot check whether the quality check runs, as I have not yet updated the quality check to v1.1.

2020-09-02 12:37 UTC, LiamDBailey commented
No worries, I think we'll list it for now and worry about the quality check once it's updated to v1.1

2020-09-02 12:38 UTC, merged